### PR TITLE
Refactor color scheme

### PR DESCRIPTION
**Pull request by Pr0pHesyer**
1.Add dynamic theme,including lightScheme & darkScheme,set it default….This has improved readability, especially in sunlight.
2.Use a switch to toggle oldScheme. But oldScheme has some bugs,such as NavigationBar color.I highly suggest to remove the support of oldScheme. 3.Radar view doesn't has a high contrast than oldScheme,but I would not to use Error color for high contrast. 4.Move Theme.kt to subpackage theme.
5.Add monochrome laucher icon.
6.Dynamic map filter.
7.themes.xml may be useless but I didn't modify.

May fix some of #88 ?

### CODE REVIEW

**Comment by rt-bishop** [comment]
Hey there @Pr0pHesyer. Thanks so much for your contribution!

There are a few things worth mentioning. First, I recently became a father, so all my projects are currently on pause. Look4Sat's devel branch is a Compose conversion which is a WIP and I don't even know when I am able to finalize and release it.

Second, I don't have the intention to support the light theme, dynamic colors or the theme switcher for now. And 100% not with the colors you supplied. I'm not sure what the app will look like by the time I'm done with Compose conversion, I'm sure a lot of code will be moved and refactored. So I can merge your PR just so your contribution is not lost, but most of the code you wrote if not all will probably be deleted by the time v4 of the app comes to release. Are you happy with that?

P.S. themes.xml file is used for Jetpack SplashScreen support, so it's not that useless. But yeah, one day everything will hopefully be in Compose and we say goodbye to most of those xmls. However AndroidManifest.xml is probably going to stay, ha-ha.

**Comment by Pr0pHesyer** [comment]
Congratulations on becoming a father.

The WIP has taken shape,maybe someone else can help? Can see some ideas.

I may fork a banch to support light scheme after 4.0,my eyes can't stand darr/black.

P.S. icon.xml such as launcher logo may still stay ？lol

**Comment by rt-bishop** [comment]
Thanks so much! It's a whole new world for my family =)

I'm totally happy with your PR, it's just I'm not sure when the Compose version will get to release and whether your code will stay at all in the state it currently is. I'll definitely merge it as at least the monochrome icon is a nice addition. 

Although as Compose branch is a WIP and if you can't stand dark colors, I'd suggest making similar changes locally to [main](https://github.com/rt-bishop/Look4Sat/tree/main) branch. That branch basically depicts what is currently released in Google Play and is a much more functional version of the app than Compose WIP. It's also worth mentioning that it's still a view-based implementation and is using Material2 components.

**Comment by Pr0pHesyer** [comment]
I closed this PR because it might have hindered development. It has now been merged.
Well,73 for your family

**Pull request merged**
